name: Release
on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]
jobs:
  release:
    name: Release
    environment: staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run package
        env:
          CL_CLIENT_ID: ${{ secrets.CL_CLIENT_ID }}
          CL_ENDPOINT: ${{ secrets.CL_ENDPOINT }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
          NEXT_PUBLIC_SANITY_TOKEN: ${{ secrets.NEXT_PUBLIC_SANITY_TOKEN }}
          BUILD_LANGUAGES: ${{ vars.BUILD_LANGUAGES }}
          BUILD_CMS: ${{ vars.BUILD_CMS }}
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
